name: java-build
run-name: java-build is java-build ing
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle' # See 'Supported distributions' for available options
        java-version: '21'
    - run: java -Xmx1024M -Xms1024M -jar paper-1.8.8-445.jar
