steps:
- uses: actions/checkout@v4
- uses: actions/setup-java@v4
  with:
    distribution: 'oracle' # See 'Supported distributions' for available options
    java-version: '21'
- run: java -Xmx1024M -Xms1024M -jar EaglerXBungee-1.0.9.jar
